---
- name: Save custom test
  become: true
  hosts: localhost
  connection: local
  vars:
    test_id: "empty"
    test_number: "empty"
    url: "empty"
    file_name: "empty"

  tasks:
    # Get to customs directory
    - name: Create directory if doesnt exist
      file:
          path: customs/{{ test_id }}/{{ test_number }}
          state: directory

    # Download custom code
    - name: Example clone of a single branch
      ansible.builtin.git:
        repo: "{{ url }}"
        dest: customs/{{ test_id }}/{{ test_number }}
        version: master
        force: yes

    - name: Set permissions
      file:
        path: customs/{{ test_id }}/{{ test_number }}
        recurse: yes
        mode: "0744"
