- name: Target setup playbook
  hosts: all
  become: true
  vars:
    test: "All -ShowDetailsBrief"
  tasks:
    - name: Check for single host
      fail: msg="Single host check failed."
      when: "{{ play_hosts|length }} != 1"

    - debug: msg='I got executed!'
    # install Extra Packages for Enterprise Linux
    - name: Install EPEL package RedHat
      ansible.builtin.yum:
        name:
          - epel-release
          - sshpass
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install EPEL package Debian
      apt:
        name:
          - sshpass
        state: present
      when: ansible_os_family == "Debian"  

  # install powershell
    - name: Download powershell repo RedHat
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/config/rhel/7/prod.repo
        dest: /etc/yum.repos.d/
      when: ansible_os_family == "RedHat"

    - name: Install Powershell RedHat
      ansible.builtin.yum:
        name: powershell
        state: present 
      when: ansible_os_family == "RedHat"

    - name: Download Powershell Debian
      get_url:
        url: https://github.com/PowerShell/PowerShell/releases/download/v7.4.2/powershell_7.4.2-1.deb_amd64.deb
        dest: /tmp/powershell_7.4.2-1.deb_amd64.deb
        force_basic_auth: yes
      when: ansible_os_family == "Debian"

    - name: Install Powershell Debian
      ansible.builtin.apt:
        deb: /tmp/powershell_7.4.2-1.deb_amd64.deb
      when: ansible_os_family == "Debian"


  # install invoke-atomic
    - name: Download Invoke Atomic
      get_url:
        url: https://raw.githubusercontent.com/redcanaryco/invoke-atomicredteam/master/install-atomicredteam.ps1
        dest: /tmp/install-atomicredteam.ps1
        force_basic_auth: yes

    - name: Install InvokeAtomic
      shell: . /tmp/install-atomicredteam.ps1; Install-AtomicRedTeam -getAtomics -Force 
      args:
        executable: /usr/bin/pwsh
      register: result

    - name: Debug
      debug:
        var: result

    - name: Install rsyslog on CentOS
      become: true
      yum:
        name: rsyslog
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install rsyslog on Debian
      become: true
      apt:
        name: rsyslog
        state: present
      when: ansible_os_family == "Debian"

    - name: Download file to rsyslog
      become: true
      get_url:
        url: "https://pastebin.com/raw/jTtrkJf8"
        dest: "/var/log/secmon.conf"

    # The nice way with service or ansible.builtin.systemd_service did not work.
    - name: Restart rsyslog
      become: true
      ansible.builtin.command:
        argv:
          - systemctl
          - restart
          - rsyslog

